sudo: false
language: c
os: osx

addons:
  homebrew:
    packages:
    - z3
    - stack
    - upx

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal/
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/brittany/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/HaRe/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/core/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/haskell-lsp-types/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/cabal-helper/.stack-work
  - $TRAVIS_BUILD_DIR/hie-plugin-api/.stack-work
  timeout: 800
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/.stack-work/logs/

stages:
  - setup
  - dependencies
  - test
  - deploy

jobs:
   include:
     - stage: setup
       env: GHC_VER="8.6.5"
       script: &setup
         - ls .stack-work/install/*/*/*/bin/hie || true
         - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml setup
         # Build a big package to offload the next stage from doing too much work
         - stack --stack-yaml=stack-$GHC_VER.yaml build lens

     - stage: dependencies
       env: GHC_VER="8.6.5"
       script: &dependencies
         - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml build --only-dependencies

     - stage: test
       env: GHC_VER="8.6.5"
       script: &test
         - stack --no-terminal --stack-yaml=stack-$GHC_VER.yaml install

     - stage: deploy
       env: GHC_VER="8.6.5"
       script: &deploy
         - mkdir -p $HOME/hie-macos
         - cp .stack-work/install/*/*/$GHC_VER/bin/hie $HOME/hie-macos
         - cp .stack-work/install/*/*/$GHC_VER/bin/hie-wrapper $HOME/hie-macos
         - upx --best $HOME/hie-macos/hie
         - upx --best $HOME/hie-macos/hie-wrapper
         - tar czf "hie-$GHC_VER-Darwin.tar.gz" $HOME/hie-macos
       deploy: &upload
         provider: releases
         api_key:
           secure: DODhl2VsorSM/g6sZcWL2i+BnQYsuHBiYulaSAr7O+VK3/giEdzOAH/NaNFe1W4moe+QvsYT89lz3YM6e6j2xyY4APXYoo+wd92Q7/6E4+7cTzlGiMsIRHwFwCl7TUemRIvE0PXxNyorHIcz7099bRfkRMU1M97TSYra3oLohMom5NcKPi6YV+LtkEHjz6tJkS61Dd4wpUHjIcTSmt7c/tNwTvs0bB/gpfkCNBVfkMn2Sm+4fl+h/IAswvTotm79T5wzruZf3Zx4mgoVJWYOMbGxwMbwXUZ5OfeaIxX4R7nCLaft0wCEBSmJdiFsBAW+l5rjwQXJBwIxo5WghoMrtvooQEdZqU43Y9BtI2Rpdd8m+P3eKKxi1ekXRQHP1NdweL2RfgvVgGEPdzvhMjgJnR2WCvzmqLP3GYAuGqENVrcDaOZOjPPU1rs3xyPJVnSzhMRMMANm8/xZUAM3ub5mWP5kqt9zFrsqRRvSBpqe4lZ0Hx/ds5lyXlgoXpX2wuL/d5ItoMgeiMEHa5kY7nIAk8H9ePy65415P9n2VLP1F4dYFpw0tO2aHpkKNH/SpLfk4DyS3aQE0Fu8o3yzFhk6+W5x47LqG9l0ESuPsN3vK8uTnfUFLZwxmDeBewKYVGIJsjSniMJfK9eqslG+QZ4SC/RvgTmyT8KDcWu4WIk66a0=
         file:
           - "hie-$GHC_VER-Darwin.tar.gz"
         skip_cleanup: true
         draft: true
